# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'MobileFlorist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileFlorist
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Stripe'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
end
